### ISSUE TITLE
Problem of multilingual support

### ISSUE THREAD

**Issue by urakubo** [urakubo/UNI-EM#10]
If folder names include Japanese language, an abnormal termination with the following msg occurs when 2D CNN training is executed (ver 0.82).

{'Image Folder': 'C:/Users/urakubo/Desktop/Dojo_Devel/Example2CNNテスト/TrainingImages', 'Segmentation Folder': 'C:/Users/urakubo/Desktop/Dojo_Devel/Example2CNNテスト/GroundTruth', 'Model Folder': 'C:\\Users\\urakubo\\Desktop\\UNI-EM0.82_CPU\\data\\model_tensorflow', 'Batch Size': '1', 'Loss Function': 'softmax', 'Maximal Epochs': '2000', 'Display Frequency': '200', 'Augmentation': 'fliplr, flipud, transpose', 'Save Parameters': 'C:\\Users\\urakubo\\Desktop\\UNI-EM0.82_CPU\\data\\parameters\\Training_2D.pickle', 'Load Parameters': 'C:\\Users\\urakubo\\Desktop\\UNI-EM0.82_CPU\\data\\parameters\\Training_2D.pickle', 'U depth': '8', 'N res blocks': '9', 'N highway units': '9', 'N dense blocks': '5', 'N dense layers': '5', 'Network': 'unet'}
Target file to check color type :  C:/Users/urakubo/Desktop/Dojo_Devel/Example2CNNテスト/TrainingImages\0049.png
Traceback (most recent call last):
  File "UNI-EM\segment\_2D_DNN\TrainingTab.py", line 192, in _ExecuteTraining
  File "UNI-EM\segment\_2D_DNN\ExecuteTraining.py", line 58, in __init__
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by urakubo** [comment]
Solved.
